name: swift

on: [push]

jobs:
  build:

    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Test
        run: cd swift && make test

      - name: iOS 
        run: cd swift && make ios-fat

      - name: macos 
        run: cd swift && make macos 
